### ISSUE TITLE
About the code "Vis2"

### ISSUE THREAD

**Issue by zhongyuan1995** [CarolineMagg/DeepImagePrior_Python#1]
I've seen from your project page https://www.cg.tuwien.ac.at/courses/Visualisierung2/HallOfFame/2020/projects/magnus2017-Caroline%20Magg_44328736_assignsubmission_file_/Vis2-master/framework2/Vis2/html/index.html that you would like to provide the source code. May I still be able to access it somewhere? It would be great if you can share the code with me, I'm working in the same research line. Thanks a lot!

**Comment by CarolineMagg** [comment]
I changed the visibility of the project, you should now be able to access the code. I hope our project helps you!

**Comment by zhongyuan1995** [comment]
thanks! I can access the repo now.
